#cloud-config
users:
  - name: username
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMkEvbSeFJrsCoRM3Ge/5SLf24QM4npF0H7FVLIuYdGu4Olj5iOA+yTSnGPoUqLtdJc+bdJT6kswTxENcbyjeHMzjWvq3cVsCWqbTvBUBe65pUBQ/JqFlMOlKKe5S+iXQOqm3/+xO5dECeQJ2xqdQgXAKPOmXfb3nvMyPOi2iutiWw7q7AhQeJrLvUyVXpgKGWGmKbpHiboeRxZJ1kiaYgTmfPry0obZ+ORJY3zfz1XZHrULWARDJDr0QX9Let6b/p6extpyz5wEKLv6OHSYkr7Z0UI1HMhdNwLyj4sVgoEt7bg8Mi4OmBEkmdoSSA3HBEW+IY/8mIueiEbnzEYpbP cisadm@SMANSIBLE001
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
runcmd:
  - sed -i -e '/^Port/s/^.*$/Port 22/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin without-password/' /etc/ssh/sshd_config
  - sed -i -e '$aAllowUsers cisadm' /etc/ssh/sshd_config
config:
  user.network-config:
    version: 1
    config:
      - type: physical
        name: ens3
        subnets:
          - type: static
            ipv4: true
            address: "@@{IP_Address}@@"
            netmask: "@@{Subnet_Mask}@@"
            gateway: "@@{Gateway}@@"
            control: auto
      - type: nameserver
        address: "@@{DNS_Servers_1}@@, @@{DNS_Servers_2}@@"  
        
        
